# Listed below is the format for listing the candidates to their respective positions and partylist
# If ever a candidate is running without a partylist register them as "Independent (IND)" for clearance

# This datasheet is encouraged to be modified for ease of changing names within the website

settings:
  texts:
    browser_tab_text: "eBoto Voting Result"
    red_title: "2025 SSG GENERAL ELECTIONS"
  sources:
    web_emblem: "assets/logo-emblem/mcm_emblem.png"
    eboto_emblem: "assets/logo-emblem/eboto_logo.png"